version: 1.0.{build}

image: Visual Studio 2022

environment:
  FLUTTER_CHANNEL: stable
  FLUTTER_ROOT: C:\tools\flutter

install:
  # Installer Flutter si pas déjà
  - ps: |
      if (-Not (Test-Path $env:FLUTTER_ROOT)) {
        Write-Host "Installing Flutter..."
        Invoke-WebRequest https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.13.10-stable.zip -OutFile flutter.zip
        Expand-Archive flutter.zip -DestinationPath C:\tools
      }
  - ps: $env:Path += ";$env:FLUTTER_ROOT\bin"

  # Installer dépendances Flutter
  - flutter doctor
  - flutter pub get

  # Installer Inno Setup
  - ps: |
      if (-Not (Test-Path "C:\Program Files (x86)\Inno Setup 6\ISCC.exe")) {
        Invoke-WebRequest https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe -OutFile innosetup.exe
        Start-Process innosetup.exe -ArgumentList "/SILENT","/NOCANCEL","/SUPPRESSMSGBOXES","/NORESTART" -Wait
      }

build_script:
  - ps: flutter build windows --release

  # @Choix dev / prod selon message de commit
  - ps: |
      if ($env:APPVEYOR_REPO_COMMIT_MESSAGE -like "*[prod]*") {
        Copy-Item installer/windows_installer_prod.iss installer/windows_installer.iss -Force
        Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "installer/vc_redist.x64.exe"
      } else {
        Copy-Item installer/windows_installer_dev.iss installer/windows_installer.iss -Force
      }

  # Créer l'installer
  - ps: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer/windows_installer.iss'

artifacts:
  - path: installer\Output\*.exe
    name: ShopManager
